"""caching of avatar hashes

Revision ID: 551f57673d06
Revises: 18f1e971a3ce
Create Date: 2022-08-29 09:47:09.874392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551f57673d06'
down_revision = '18f1e971a3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
